# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
    - dev

variables:
- group: dev-variables

stages:
- stage: Build
  displayName: Build and publish
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
        
    - script: dotnet build --configuration Release
      displayName: 'Dotnet build Release'
      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      displayName: 'Publish'
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish artifact'

- stage: Dev
  variables:
    ConnectionStrings.DefaultConnection: $(ConnectionStringDev)
  displayName: Deploy to Dev
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')
  jobs:
    - deployment: DeployDev
      environment: DEV
      pool:
        vmImage: ubuntu-latest  
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: DotNetCoreCLI@2
              displayName: Install dotnet-ef
              inputs:
                command: 'custom'
                custom: 'tool'
                arguments: 'install --global dotnet-ef'

            - script: dotnet tool restore
              displayName: 'Dotnet tool restore'
                
            - task: DownloadBuildArtifacts@0
              displayName: Download artifact
              inputs:
                buildType: 'current'
                project: '474863c3-dee8-420d-b794-4679642f5427'
                artifactName: 'drop'
                buildVersionToDownload: 'latest'
                downloadType: 'single'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: FileTransform@1
              displayName: 'File transformation: appsettings.json'
              inputs:
                folderPath: '$(System.ArtifactsDirectory)/**/*.zip'
                fileType: 'json'
                targetFiles: '**/appsettings.json'
          
            - script: |
                ls
                dotnet-ef database update --connection "$(ConnectionStringDev)"
              displayName: 'Update Database'

- stage: Prod
  variables:
    ConnectionStrings.DefaultConnection: $(ConnectionStringProd)
  displayName: Deploy to Prod
  condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
    - deployment: DeployProd
      environment: PROD
      pool:
        vmImage: ubuntu-latest  
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureKeyVault@2
              condition: contains(variables['Build.SourceBranch'], 'refs/heads/x')
              inputs:
                azureSubscription: 'name'
                KeyVaultName: 'azure-mealforfamily-keys'
                SecretsFilter: '*'
                RunAsPreJob: true
            - checkout: self
            - task: DotNetCoreCLI@2
              displayName: Install dotnet-ef
              inputs:
                command: 'custom'
                custom: 'tool'
                arguments: 'install --global dotnet-ef'

            - script: dotnet tool restore
              displayName: 'Dotnet tool restore'
                
            - task: DownloadBuildArtifacts@0
              displayName: Download artifact
              inputs:
                buildType: 'current'
                project: '474863c3-dee8-420d-b794-4679642f5427'
                artifactName: 'drop'
                buildVersionToDownload: 'latest'
                downloadType: 'single'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: FileTransform@1
              displayName: 'File transformation: appsettings.json'
              inputs:
                folderPath: '$(System.ArtifactsDirectory)/**/*.zip'
                fileType: 'json'
                targetFiles: '**/appsettings.json'
          
            - script: |
                ls
                dotnet-ef database update --connection "$(ConnectionStringProd)"
              displayName: 'Update Database'
                
            - task: AzureWebApp@1
              displayName: 'Deploy to Web App'
              inputs:
                azureSubscription: '$(ServiceConnection)'
                appType: 'webAppLinux'
                appName: '$(AppServiceNameProd)'
                package: '$(System.ArtifactsDirectory)/**/*.zip'


  